# Generated by Django 2.0.4 on 2018-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_auto_20180425_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Ingredient'),
        ),
    ]
