# Generated by Django 2.0.4 on 2018-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0004_auto_20180518_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
