# Generated by Django 2.2.12 on 2020-04-20 09:20

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import private_storage.storage.files
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tags', models.TextField(blank=True, verbose_name='tags')),
                ('image', core.fields.PrivateImageField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=recipes.models.recipe_image_path, verbose_name='image')),
                ('sources', models.TextField(blank=True, verbose_name='sources')),
                ('servings', models.FloatField(blank=True, null=True, verbose_name='servings')),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'very easy'), (2, 'easy'), (3, 'medium'), (4, 'hard'), (5, 'very hard')], null=True, verbose_name='difficulty')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipe_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_recipe_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-active', '-modified'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipesection_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_recipesection_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='recipes.Recipe')),
            ],
            options={
                'ordering': ('-active', '-modified'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('preparation_method', models.CharField(max_length=64, verbose_name='preparation method')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('optional', models.BooleanField(default=False, verbose_name='optional')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sectioningredient_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_recipes', related_query_name='in_recipe', to='ingredients.Ingredient')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sectioningredient_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredient', to='recipes.RecipeSection')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_ingredients', related_query_name='section_ingredient', to='ingredients.IngredientUnit')),
            ],
            options={
                'ordering': ('-active', '-modified'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('description', models.TextField(verbose_name='description')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('duration_type', models.CharField(blank=True, choices=[('prep', 'prep'), ('cook active', 'cook (active)'), ('cook passive', 'cook (unattended)')], max_length=16, verbose_name='duration type')),
                ('image', core.fields.PrivateImageField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=recipes.models.section_direction_image_path, verbose_name='image')),
                ('optional', models.BooleanField(default=False, verbose_name='optional')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sectiondirection_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sectiondirection_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', related_query_name='direction', to='recipes.RecipeSection')),
            ],
            options={
                'ordering': ('-active', '-modified'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='scaling_ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scaled_recipe', to='recipes.SectionIngredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PreparationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metric_size', models.CharField(blank=True, max_length=64, verbose_name='metric size')),
                ('imperial_size', models.CharField(blank=True, max_length=64, verbose_name='imperial size')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_preparationmethod_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_preparationmethod_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-active', '-modified'),
                'abstract': False,
            },
        ),
    ]
