# Generated by Django 2.2.12 on 2020-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200420_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='scaling_ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='scaled_to',
            field=models.FloatField(blank=True, null=True, verbose_name='scaled to'),
        ),
    ]
