# Generated by Django 2.2.12 on 2020-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200525_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesection',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sectioningredient',
            name='preparation_method',
            field=models.CharField(blank=True, max_length=64, verbose_name='preparation method'),
        ),
    ]
