// Messages
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";

// Auth
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Ingredients
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENT = "GET_INGREDIENT";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const SEARCH_INGREDIENTS = "SEARCH_INGREDIENTS";
export const GET_INGREDIENT_CATEGORIES = "GET_INGREDIENT_CATEGORIES";
export const GET_INGREDIENT_UNITS = "GET_INGREDIENT_UNITS";

// Recipes
export const GET_RECIPES = "GET_RECIPES";
export const GET_RECIPE = "GET_RECIPE";
export const GET_DURATION_TYPES = "GET_DURATION_TYPES";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
