# Generated by Django 2.2.12 on 2020-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='energy_kj',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy (kJ)'),
        ),
    ]
