# Generated by Django 2.2.12 on 2020-04-20 09:20

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ingredients.models
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tags', models.TextField(blank=True, verbose_name='tags')),
                ('image', core.fields.PrivateImageField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=ingredients.models.ingredient_image_path, verbose_name='image')),
                ('usda_fdc_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='usda fdc id')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('usda_fdc_id', 'title'),
            },
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('shorthand', models.CharField(blank=True, max_length=16, verbose_name='shorthand')),
                ('unit_type', models.CharField(choices=[('weight', 'unit weight'), ('volume', 'unit volume')], max_length=16, verbose_name='unit type')),
                ('unit_system', models.CharField(choices=[('custom', 'unit custom'), ('metric', 'unit metric'), ('imperial_uk', 'unit imperial uk'), ('imperial_us', 'unit imperial us')], default='custom', max_length=16, verbose_name='unit system')),
                ('usda_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='usda id')),
                ('amount_in_base', models.FloatField(verbose_name='amount in base unit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ingredientunit_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', related_query_name='unit', to='ingredients.Ingredient')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ingredientunit_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ('ingredient', 'unit_system', 'unit_type', 'amount_in_base'),
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='datetime created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime modified')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='description')),
                ('image', core.fields.PrivateImageField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=ingredients.models.ingredient_category_image_path, verbose_name='image')),
                ('usda_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='usda id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ingredientcategory_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ingredientcategory_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'Ingredient Category',
                'verbose_name_plural': 'Ingredient Categories',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', related_query_name='ingredient', to='ingredients.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ingredient_objects', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ingredient_objects', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredient', to=settings.AUTH_USER_MODEL),
        ),
    ]
